spring.application.name=Stardew-Valley-Perfection-Tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/stardew
spring.datasource.name=stardew
spring.datasource.username=postgres
spring.datasource.password=postgres1


#spring.profiles.active=@spring.profiles.active@